### ISSUE TITLE
Peer-to-peer Code Review (23/1/2020)

### ISSUE THREAD

**Issue by Kyle-Law** [Kyle-Law/Positioning-and--Floating-Elements#3]
Please leave any comments / suggestions :)

**Comment by patriciachrysy** [comment]
Kyle good job and clean code as always, especially the HTML. I saw that you grided the main content when you did not need to. Actually, the " aside section " this only on a particular part of the page, you can check on the original. And another thing is the big drawn image with text. Actually, it is a whole unified image where you have to position the text, I was about to ask you how to do that but i saw you skipped it :-) lol. And yes there is a way to build the aside with float, not as good as yours but there is.

**Comment by dili021** [comment]
Amazing work! The only thing I noticed in the time I had is that you should add margin/padding-bottom to the body so the text doesn't get covered by the footer.

**Comment by Kyle-Law** [comment]
Thanks, @patriciachrysy and @dili021 for your suggestions!

**Comment by Kyle-Law** [comment]
@dili021 Your suggestion has been implemented!  Thanks bro 👍
